### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by umairwaheed2244** [yawkale/nop-umbraco-integration#13]
I am facing some issues, I think that system is integrated and it's opening the site which is connected nop site which is connected to umbraco but when a product or news is clicked on an error comes which is given below:
Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.

Line 14:   Line 15:
Compiler Error Message: CS1061: 'Umbraco.Web.PublishedContentModels.Product' does not contain a definition for 'Photos' and no extension method 'Photos' accepting a first argument of type 'Umbraco.Web.PublishedContentModels.Product' could be found (are you missing a using directive or an assembly reference?).

**Comment by yawkale** [comment]
Umbraco try to generate a model for document type, you can disable it by changing the key in web.config file
 <add key="Umbraco.ModelsBuilder.Enable" value="false" />
