### ISSUE TITLE
Unable to login on demo site

### ISSUE THREAD

**Issue by nielsodgaard** [yawkale/nop-umbraco-integration#17]
Hi,

I am unable to login into umbraco backoffice on the demo site. 
Could you make sure that the account is not locked out and the password haven't been changed?

**Comment by yawkale** [comment]
Hi, please try again, looks work for me
Umbraco back office login: 
**username**: test 
**password**: test1234
**url** http://umbraco.nopintegra.com/umbraco

**Comment by nielsodgaard** [comment]
Works now, guess I must have done something wrong. Thanks for your help
