### ISSUE TITLE
Nop multistore support

### ISSUE THREAD

**Issue by alecrt** [yawkale/nop-umbraco-integration#9]
Do you think it woul’d be possible to have a single nop multistore backend with multiple umbraco frontends?

**Comment by RobertCarlaw** [comment]
Yes but you’d have to extend this api. 
NOP contains the notion of multi store which is unique by storeID the api would need to pass this around.

**Comment by alecrt** [comment]
Yep.

Do you know if Nop API plug-in already support it storeId param?

Inviato da iPhone

Il giorno 31 mar 2018, alle ore 11:20, Robert Carlaw <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Yes but you’d have to extend this api.
NOP contains the notion of multi store which is unique by storeID the api would need to pass this around.

**Comment by yawkale** [comment]
Nop API plugin, return store_id on select and on created, we are working to add support from our side
